# Generated by Django 4.2 on 2023-12-15 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="content_key",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                upload_to="video",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="preview",
            field=models.ImageField(upload_to="preview"),
        ),
    ]
