# Generated by Django 4.1.5 on 2023-05-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='profile',
        ),
    ]
